spring.application.name=Bank-Of-Lodaeron

spring.datasource.url=jdbc:mysql://localhost:3306/BankOfLordaeronDB
spring.datasource.username=root
spring.datasource.password=LainIwakura

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
